/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        gray: {
          "100": "#fdfdfd",
          "200": "#8e8e8e",
          "300": "#202020",
          "400": "#1f1f1f",
          "500": "#1d1d1d",
          "600": "#181818",
        },
        "primary-100": "#5c27c0",
        darkorchid: "#824de6",
        snow: "#fffbfb",
        white: "#f7f7f7",
        black: "#1c1c1c",
        "primary-300": "#eee5ff",
        "neutrals-white": "#fafafa",
        "neutrals-300": "#6a6a6a",
        darkslategray: "#3b3b3b",
        black1: "#000",
        white1: "#fff",
        dimgray: "#5b5b5b",
        goldenrod: "#ffb649",
        plum: "#ad93df",
        whitesmoke: "#f6f6f6",
      },
      spacing: {},
      fontFamily: {
        poppins: "Poppins",
        "garnett-semibold": "'Garnett Semibold'",
        "garnett-regular": "'Garnett Regular'",
        "garnett-medium": "'Garnett Medium'",
        "space-grotesk": "'Space Grotesk'",
        "garnett-light": "'Garnett Light'",
        "gilroy-regular": "Gilroy-Regular",
        actor: "Actor",
        outfit: "Outfit",
      },
      borderRadius: {
        xl: "20px",
        "3xs": "10px",
        "8xs": "5px",
        "96xl": "115px",
        "7xs-7": "5.7px",
      },
    },
    fontSize: {
      "5xl": "24px",
      lg: "18px",
      "23xl": "42px",
      "15xl": "34px",
      "6xl": "25px",
      base: "16px",
      "4xl": "23px",
      "31xl": "50px",
      "21xl": "40px",
      "11xl": "30px",
      "19xl": "38px",
      lgi: "19px",
      "9xl": "28px",
      "3xl": "22px",
      "13xl": "32px",
      sm: "14px",
      xl: "20px",
      "smi-3": "12.3px",
      "5xl-9": "24.9px",
      "10xl": "29px",
      "29xl": "48px",
      "35xl": "54px",
      "xs-4": "11.4px",
      "16xl-5": "35.5px",
      inherit: "inherit",
    },
    screens: {
      mq1400: {
        raw: "screen and (max-width: 1400px)",
      },
      mq1125: {
        raw: "screen and (max-width: 1125px)",
      },
      mq825: {
        raw: "screen and (max-width: 825px)",
      },
      mq450: {
        raw: "screen and (max-width: 450px)",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
